// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WorkweixinTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void workweixin() {
    driver.get("https://work.weixin.qq.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("企业登录")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".qrcode_login_content")).click();
    driver.findElement(By.cssSelector(".qrcode_login_content")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".login_selectBiz_item:nth-child(1) img")).click();
    driver.findElement(By.cssSelector(".index_service_cnt_itemWrap:nth-child(1) .index_service_cnt_item_title")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.cssSelector(".member_edit_cover")).click();
  }
}
